
language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - master

env:
  - GO111MODULE=on

go_import_path: github.com/shadyzoz/goemitter

script:
  - go test ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
